var verifyNumber = (number) => {
var regex = /^((\+92)|(0092))-{0,1}\d{3}-{0,1}\d{7}$|^\d{11}$|^\d{4}-\d{7}$/;//regex gernated by chatGPT to test pakistani mobile numbers

if(regex.test(number.value)){//testing the value against the regex to verify that the value conforms
     //show invalid input message
     number.setCustomValidity("");//sets the control's validity as valid
     return true;
}
else{
     
     //set field invalid
     number.setCustomValidity('Invalid Phone Number');//if the value does not conform then marks the control as invalid

     return false;

}    
    
}


var verifyAddress = () =>{//method to veify address
     var address = document.getElementById('address');
     var regex = /^[a-zA-Z0-9\s,'-]*$/;//regex generated by chatGPT to test address's value
     
     if(regex.test(address.value)){//test the address's value against the addess regex
          address.setCustomValidity("");//if it conforms then mark the field as valid
          return true;
     }
     else{
          address.setCustomValidity('Invalid Address');//mark the field as invalid
          return false;
     }
}

var VerifyCard= (cardInput)=>{//method to verfy the card entered by the user
     //remove all - from cardInput's value
     var card = cardInput.value.replace(/-/g,'');//remove all the '-' in the value
     if(typeof(parseInt(card)) ==  number){//convert it to integer
          cardInput.setCustomValidity("");//mark the field as valid
          return true;
     }
     else{
          cardInput.setCustomValidity('Invalid Card Number');//mark the field as invalid
          return false;
     }

}

document.getElementById('card').addEventListener("keydown",() => {//dynamically add - to the card's value (change event did not work properly)
     var cardInput = document.getElementById('card');//get the control 
//dynamically add a - after every 4 characters entered
     if((cardInput.value.length+1) % 5 == 0 && cardInput.value.length != 19 ){//after every 4 characters entered adds a - to the value
          cardInput.value += '-';
     }
});



document.getElementById('submit').addEventListener('click',() =>{//form submission event handler
     verifyNumber(document.getElementById('phone'));
     VerifyCard(document.getElementById('card'));
     verifyAddress();

  
});




